### ISSUE TITLE
Enable automatic tagging

### ISSUE THREAD

**Issue by fredemmott** [facebookincubator/fb303#2]
e.g. folly, proxygen, and (formerly) Thrift are given consistent tags weekly by TagIt.

As HHVM depends on the whole lot, these tags are useful for updating first-party dependencies.

Given that Proxygen now depends on fb303, it would be useful for HHVM if fb303 had these tags rather than having to manually find a roughly-corresponding rFBS, then a roughly corresponding github commit for it.

**Comment by yfeldblum** [comment]
Do it.

Closing the public issue because this is related to internal config.
